AllCops:
  NewCops: enable
  TargetRubyVersion: 2.0

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 80
  Exclude:
    - "spec/**/*"

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AssignmentInCondition:
  Enabled: false

Lint/HashCompareByIdentity:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  CountComments: true
  Max: 25
  AllowedMethods: []
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 1500

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/tty-option.rb"

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/FetchEnvVar:
  AllowedVars:
    - COVERAGE

Style/HashTransformKeys:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/ParallelAssignment:
  Enabled: false

Style/PreferredHashMethods:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  Enabled: false
